
/**
* FileInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* viernes 18 de noviembre de 2022 11:08:31 AM CST
*/

public interface FileInterface extends FileInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileInterface
