
/**
* FileInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* viernes 18 de noviembre de 2022 11:08:31 AM CST
*/

public interface FileInterfaceOperations 
{
  byte[] downloadFile (String fileName);
} // interface FileInterfaceOperations
